export const RECEIVE_PLANET_DATA = 'RECEIVE_PLANET_DATA'
export const RECEIVE_RESIDENTS = 'RECEIVE_RESIDENTS'
export const LOADING_DATA = 'LOADING_DATA'
export const LOAD_RESIDENT_SPECIES = 'LOAD_RESIDENT_SPECIES'
